//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazaAwionika.Web {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BazaAwionika.Web.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodatowe Informacje.
        /// </summary>
        internal static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nr. samolotu.
        /// </summary>
        internal static string AircraftId {
            get {
                return ResourceManager.GetString("AircraftId", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa bazy danych.
        /// </summary>
        internal static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Data modyfikacji.
        /// </summary>
        internal static string DateAdd {
            get {
                return ResourceManager.GetString("DateAdd", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Data wykonania.
        /// </summary>
        internal static string DateExecution {
            get {
                return ResourceManager.GetString("DateExecution", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Następne sprawdzenie.
        /// </summary>
        internal static string DateExpiration {
            get {
                return ResourceManager.GetString("DateExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pozostało dni.
        /// </summary>
        internal static string DaysRemaining {
            get {
                return ResourceManager.GetString("DaysRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nalot całkowity.
        /// </summary>
        internal static string FlightHours {
            get {
                return ResourceManager.GetString("FlightHours", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nalot samolotu przy zabudowie.
        /// </summary>
        internal static string FlightHoursAircraftInstallation {
            get {
                return ResourceManager.GetString("FlightHoursAircraftInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nalot łożysk przy zabudowie na samolot.
        /// </summary>
        internal static string FlightHoursBearings {
            get {
                return ResourceManager.GetString("FlightHoursBearings", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Następne sprawdzenie łożysk.
        /// </summary>
        internal static string FlightHoursBearingsExpiration {
            get {
                return ResourceManager.GetString("FlightHoursBearingsExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nalot szczotek przy zabudowie na samolot.
        /// </summary>
        internal static string FlightHoursBrushes {
            get {
                return ResourceManager.GetString("FlightHoursBrushes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Następne sprawdzenie szczotek.
        /// </summary>
        internal static string FlightHoursBrushesExpiration {
            get {
                return ResourceManager.GetString("FlightHoursBrushesExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pozostałość nalotu łożysk.
        /// </summary>
        internal static string FlightHoursBrushesRemainFlightHoursBearingsRemaining {
            get {
                return ResourceManager.GetString("FlightHoursBrushesRemainFlightHoursBearingsRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pozostałość nalotu szczotek.
        /// </summary>
        internal static string FlightHoursBrushesRemaining {
            get {
                return ResourceManager.GetString("FlightHoursBrushesRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pozostałość nalotu do ostrzeżenia 1.
        /// </summary>
        internal static string FlightHoursCaution {
            get {
                return ResourceManager.GetString("FlightHoursCaution", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pozostałość nalotu do ostrzeżenia 3.
        /// </summary>
        internal static string FlightHoursError {
            get {
                return ResourceManager.GetString("FlightHoursError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wykonanie.
        /// </summary>
        internal static string FlightHoursExecution {
            get {
                return ResourceManager.GetString("FlightHoursExecution", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nast. sprawdzenie.
        /// </summary>
        internal static string FlightHoursExpiration {
            get {
                return ResourceManager.GetString("FlightHoursExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nalot agregatu przy zabudowie na samolot.
        /// </summary>
        internal static string FlightHoursOverhaul {
            get {
                return ResourceManager.GetString("FlightHoursOverhaul", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Następny remont.
        /// </summary>
        internal static string FlightHoursOverhaulExpiration {
            get {
                return ResourceManager.GetString("FlightHoursOverhaulExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pozostałość nalotu do remontu.
        /// </summary>
        internal static string FlightHoursOverhaulRemaining {
            get {
                return ResourceManager.GetString("FlightHoursOverhaulRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pozostało.
        /// </summary>
        internal static string FlightHoursRemaining {
            get {
                return ResourceManager.GetString("FlightHoursRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pozostałość nalotu do ostrzeżenia 2.
        /// </summary>
        internal static string FlightHoursWarning {
            get {
                return ResourceManager.GetString("FlightHoursWarning", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wpis aktualny?.
        /// </summary>
        internal static string IsActual {
            get {
                return ResourceManager.GetString("IsActual", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zamontowany na samolocie?.
        /// </summary>
        internal static string IsInstalled {
            get {
                return ResourceManager.GetString("IsInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wykonujący.
        /// </summary>
        internal static string Performer {
            get {
                return ResourceManager.GetString("Performer", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Numer seryjny.
        /// </summary>
        internal static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Resurs nalot.
        /// </summary>
        internal static string ServicePeriodFlightHours {
            get {
                return ResourceManager.GetString("ServicePeriodFlightHours", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Resurs w miesiącach.
        /// </summary>
        internal static string ServicePeriodTimeMonths {
            get {
                return ResourceManager.GetString("ServicePeriodTimeMonths", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pozostałośc dni do ostrzeżenie 1.
        /// </summary>
        internal static string SettingsDaysCaution {
            get {
                return ResourceManager.GetString("SettingsDaysCaution", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pozostałośc dni do ostrzeżenie 3.
        /// </summary>
        internal static string SettingsDaysError {
            get {
                return ResourceManager.GetString("SettingsDaysError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pozostałośc dni do ostrzeżenie 2.
        /// </summary>
        internal static string SettingsDaysWarning {
            get {
                return ResourceManager.GetString("SettingsDaysWarning", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nr. ustawień.
        /// </summary>
        internal static string SettingsId {
            get {
                return ResourceManager.GetString("SettingsId", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa ustawień.
        /// </summary>
        internal static string SettingsName {
            get {
                return ResourceManager.GetString("SettingsName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Numer ogonowy.
        /// </summary>
        internal static string TailNumber {
            get {
                return ResourceManager.GetString("TailNumber", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nr. użytkownika.
        /// </summary>
        internal static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
    }
}
